#Target : Dependencies 

Build : Milk_manage_main.c Milk_management.c
	gcc Milk_manage_main.c Milk_management.c -o Milk_management.out

Run : Build
	./Milk_management.out

Clean :
	rm -rf *.o *.out *.i *.s